-- 0001_core: runs, the append-only event log, and the two approval gates.
--
-- Forward-only. Never edit this file once it has been applied anywhere; add a
-- new numbered migration instead.

CREATE TABLE runs (
    id              uuid PRIMARY KEY,
    brief           text        NOT NULL,
    title           text,
    state           text        NOT NULL,
    failure_reason  text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT runs_brief_not_blank CHECK (length(btrim(brief)) > 0),

    -- The state machine's vocabulary lives in the database too, not only in
    -- app/state/machine.py. A typo in application code becomes a constraint
    -- violation rather than a run parked in a state nothing handles.
    CONSTRAINT runs_state_known CHECK (state IN (
        'created', 'specifying', 'spec_review', 'building', 'testing',
        'deploy_review', 'deploying', 'deployed', 'failed', 'cancelled'
    )),

    -- A failure reason is meaningful only on a failed run, and a failed run
    -- without one is an incident with no explanation.
    CONSTRAINT runs_failure_reason_iff_failed CHECK (
        (state = 'failed') = (failure_reason IS NOT NULL)
    )
);

CREATE INDEX runs_state_updated_at_idx ON runs (state, updated_at DESC);

COMMENT ON TABLE runs IS
    'One brief moving through spec, build, test and deploy. Primary keys are '
    'UUIDv7 generated by the application; see docs/decisions/0003-uuidv7-identifiers.md.';


CREATE TABLE events (
    id          uuid PRIMARY KEY,
    run_id      uuid        NOT NULL REFERENCES runs (id) ON DELETE RESTRICT,
    kind        text        NOT NULL,
    payload     jsonb       NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX events_run_id_id_idx ON events (run_id, id);

-- The event log is the audit trail the two approval gates are judged against.
-- It is append-only, and that is enforced here rather than by asking everyone
-- to remember. ON DELETE RESTRICT above means a run cannot be deleted out from
-- under its events either.
CREATE RULE events_no_update AS ON UPDATE TO events DO INSTEAD NOTHING;
CREATE RULE events_no_delete AS ON DELETE TO events DO INSTEAD NOTHING;

COMMENT ON RULE events_no_update ON events IS
    'events is append-only: it is the audit trail the human approval gates are '
    'judged against, so a correction is a new event, never an edit. Silently '
    'discarding the UPDATE (rather than raising) is deliberate -- a stray '
    'UPDATE from a future ORM must not be able to take down the worker.';

COMMENT ON RULE events_no_delete ON events IS
    'events is append-only. See the comment on events_no_update. Purging old '
    'events, if we ever need to, is a migration that drops this rule '
    'explicitly, in a transaction, with a reason in the ADR.';


CREATE TABLE approvals (
    id          uuid PRIMARY KEY,
    run_id      uuid        NOT NULL REFERENCES runs (id) ON DELETE RESTRICT,
    gate        text        NOT NULL,
    approved    boolean     NOT NULL,
    decided_by  text        NOT NULL,
    note        text,
    decided_at  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT approvals_gate_known CHECK (gate IN ('spec', 'deploy')),
    CONSTRAINT approvals_decided_by_not_blank CHECK (length(btrim(decided_by)) > 0)
);

-- One decision per gate per run. A second POST to the same gate loses to this
-- constraint instead of racing.
CREATE UNIQUE INDEX approvals_run_gate_key ON approvals (run_id, gate);

COMMENT ON TABLE approvals IS
    'The two human gates. Uniqueness on (run_id, gate) is what makes the '
    'approve endpoint idempotent under a double-click.';
